### ISSUE TITLE
Some vertices are missing in the `flx.aif` file in the latest version of TOMMS installed at PPPL

### ISSUE THREAD

**Issue by rhager** [SCOREC/Fusion_Public#11]
It seems like some vertices are missing from the list of vertices on faces ("non-aligned vertices") in the latest version of TOMMS installed at PPPL. I used it for an NSTX mesh and found some "glitches" in the data. I think the glitches are from errors in the flux-surface average routine stemming from the missing non-aligned vertices. Here is an image to illustrate the issue. The black crosses are the mesh vertices, the white crosses represent all vertices contained in the list of non-aligned surfaces. All crosses between flux-surfaces are supposed to be white. The missing vertices appear to be the ones in the transition layer between unstructured and on-element deep mesh.
![Screen Shot 2022-05-12 at 1 47 15 PM](https://user-images.githubusercontent.com/7051856/168138591-b32708f6-6d4c-4aea-a1e9-22b0a6c7ee30.png)

**Comment by usmanriaz07** [comment]
Apparently, the vertices on the edges of the transition layers are missing. I am looking at the issue now. I think I should be able to update you on this by tomorrow.
