### ISSUE TITLE
Wrong surfaces identified for some non-aligned vertices in flx.aif files

### ISSUE THREAD

**Issue by best0823** [SCOREC/Fusion_Public#12]
It seems surfaces are being incorrectly identified for some non-aligned vertices in flx.aif files.

I noticed this problem with the flx.aif file for a [DIII-D case](https://github.com/PrincetonUniversity/XGC-Examples/tree/master/DIII-D_132007-01300_for_ECP/input_dir) in the XGC-Examples repo. I also tried generating the mesh for the above case myself using the input files located in the [meshing](https://github.com/PrincetonUniversity/XGC-Examples/tree/master/DIII-D_132007-01300_for_ECP/input_dir/meshing) directory. I used the following executable on PPPL portal:

`/p/epsi/rpi/install/centos7-intel2019u3-openmpi4.0.3/16.0-210626/bin/tomms_meshgen`

Below are some figures from the mesh I generated for this case illustrating the problem.

I found similar issues with this [case](https://github.com/SCOREC/Fusion_Public/tree/master/samples/d3d_144981-03175_meshing_v2) from the SCOREC repo.

![example_node_1.pdf](https://github.com/SCOREC/Fusion_Public/files/9377193/example_node_1.pdf)
![example_node_2.pdf](https://github.com/SCOREC/Fusion_Public/files/9377195/example_node_2.pdf)
![example_node_3.pdf](https://github.com/SCOREC/Fusion_Public/files/9377196/example_node_3.pdf)

**Comment by rhager** [comment]
Looks like you're using an executable from 2021. Could you try this one: `/p/epsi/rpi/install/TOMMS/2022_06_23/bin/tomms_meshgen`?

**Comment by best0823** [comment]
Sure, I'll give it a try.

**Comment by ays5** [comment]
https://xgc.pppl.gov/html/meshing_tutorial.html#environment-setup

**Comment by best0823** [comment]
Looks like that was the problem - will close this issue.
Thanks @rhager and @ays5!
