### ISSUE TITLE
Sample N-g132588.00650

### ISSUE THREAD

**Issue by mdjcole** [SCOREC/Fusion_Public#2]
I am trying to run this sample

https://github.com/SCOREC/Fusion_Public/tree/master/samples/N-g132588.00650

on the PPPL cluster using:

/p/epsi/rpi/install/intel2015-openmpi1.10.3/15.0-190719dev/bin/xgc_meshge

It fails with error "xgc_meshgen: /u/sseol/develop/Fusion-pppl/xgc/genCurve.cc:1872: void get_pushed_points(double *, double, args *, double, std::vector<StartPoint, std::allocator<StartPoint>> &): Assertion `sps.size()==2' failed".

**Comment by zhangchonglin** [comment]
I could confirm this issue using my (very old) installation on SCOREC computer. @seegyoung @usmanriaz07

**Comment by usmanriaz07** [comment]
I just confirmed it. The sample is also failing at SCOREC machine too. I am working on it and will update as soon as I fix the problem.

**Comment by usmanriaz07** [comment]
The test case has been updated and works fine now.
