### ISSUE TITLE
Fusion Modeling and Meshing Tool Name

### ISSUE THREAD

**Issue by usmanriaz07** [SCOREC/Fusion_Public#3]
As we discussed in our last group meeting, we need to come up with a better name for our Tokamak tool. 

1- The tool does both modeling and meshing, so the name should be general and not specific to one thing (like we used to call it XGC meshing tool or Fusion meshing tool).
2- Secondly, this tool can be used for a  number of applications involving Tokamak geometries and meshes, so the name cannot be code specific like we earlier had XGC meshing.
3- Finally, it only targets Tokamaks and not other Fusion devices like Stellarators so the name should not suggest that it can be used for any Fusion device. 

Drop your suggestions here.

**Comment by usmanriaz07** [comment]
I was thinking about just TokaM (M for both modeling and meshing).

**Comment by kumargp** [comment]
Since the code is being used by PPPL, and co-developed by Simmetrix, I think they need to be included.

**Comment by kumargp** [comment]
I see similar other code: 
[Tokamesh : A software for mesh generation in Tokamaks](https://www.google.com/search?q=Tokamesh+%3A+A+software+for+mesh+generation+in+Tokamaks&oq=Tokamesh+%3A+A+software+for+mesh+generation+in+Tokamaks&aqs=chrome..69i57j69i60.638j0j7&sourceid=chrome&ie=UTF-8)

**Comment by usmanriaz07** [comment]
Yeah, I have seen this one before. This sounds similar to what I suggested though I was thinking of just using TokaM and not TokaMesh. Let me think of any other name.

**Comment by usmanriaz07** [comment]
@onkarsahni  Here is the Name Issue as we discussed in our last meeting

**Comment by cwsmith** [comment]
TOMMS - TOkamak Modeling and Meshing Suite ?

**Comment by usmanriaz07** [comment]
@cwsmith  This one seems a good otpion as its covering both the modeling and meshing parts in the name with focusing on the tokamak. Let's see what others have to say about this.
