### ISSUE TITLE
License error on PPPL cluster

### ISSUE THREAD

**Issue by mdjcole** [SCOREC/Fusion_Public#4]
Simmodeller gives error

Error: Code: 200 String: No license for feature advmodel

Worked yesterday.

**Comment by rhager** [comment]
There are two things you can try: i) wait an hour or so in case the license
is in use by somebody else; ii) unload and reload the RLM module.
Otherwise, this could also be connected to the system maintenance
yesterday. In that case, you'd have to open a ticket with PPPL's help desk.

**Comment by rhager** [comment]
FYI, I just opened a ticket at PPPL to have IT check the status of the
license error in case something broke during today's system maintenance.

**Comment by rhager** [comment]
This was an error in the license server at PPPL and has been resolved.
