### ISSUE TITLE
sqrt(psi) radial meshing does not work

### ISSUE THREAD

**Issue by mdjcole** [SCOREC/Fusion_Public#6]
!Choose a way of uniformity in radial direction (1: psi, 2: sqrt(psi))
radial_uniform_meshing_unit 2

This option reliably fails for all my cases that work with '1' or '-1'

**Comment by usmanriaz07** [comment]
Hi Michael,

The issue has been fixed. You can find the updated executable at:
/p/epsi/rpi/install/centos7-intel2019u3-openmpi4.0.1/15.0-200714/bin/tomms_meshgen

Let me know if you still see some issues.
