### ISSUE TITLE
Errors in flx.aif file

### ISSUE THREAD

**Issue by rhager** [SCOREC/Fusion_Public#7]
In some cases, some vertices between flux=surfaces do not appear in the list of non-aligned vertices in the flx.aif file. I suspect that this has to do with there being more than two flux-surfaces with which those vertices could be associated.
Here is an example:

<img width="750" alt="Screen Shot 2021-05-25 at 3 17 25 PM" src="https://user-images.githubusercontent.com/7051856/119556303-d43fca00-bd6c-11eb-9b2e-5900b7b597c6.png">

The solid lines indicate the flux-surfaces formed by the mesh vertices. The dots are either wall vertices or non-aligned vertices. The non-aligned vertices that do appear in the flx.aif file are marked by the orange crosses.

I'll pack up the input files for this example and post their location in this issue.

**Comment by usmanriaz07** [comment]
Are you seeing this issue with only the latest executable or it was there all along? I am asking this because I worked with flx.aif routines recently so I just want to make sure that it's not something with the latest changes in the code.

**Comment by rhager** [comment]
I think this has been there all along. I think the problem is that we never defined how to handle such points that are between two flux-curves but at least one of the flux-curve is divided into two (or more) segments by the wall curve. In such cases, I suggest to associate the vertex with the nearest segment of the divided flux-curve.

**Comment by zhangchonglin** [comment]
@rhager: I recently also encountered situation where vertex in the unstructured mesh region, is included in the non-aligned vertex list within `flx.aif` file. Not sure if this is also the case for you, just in case.

**Comment by usmanriaz07** [comment]
@rhager Can you please provide me the input files for this case?

**Comment by usmanriaz07** [comment]
@rhager I just want to verify one thing. 
When we say "non-aligned" vertices these are the vertices between any two flux curves that are not aligned? Should this contain the vertices in the wall face (face between wall curve and last flux curve) or the vertices in the private region?

**Comment by usmanriaz07** [comment]
And yes apparently the issue only appears in the cases where a flux curve is split into segments by the wall curve.

**Comment by rhager** [comment]
@usmanriaz07: The latest input I used for this case is in `/p/epsi/rhager/d3d_132007-01298_v3_20210609.tar`. The tarball includes a fixed version of the flx.aif file.

> the vertices between any two flux curves that are not aligned

Exactly. Only non-aligned vertices enclosed by two flux-curves have to be in the flx.aif file.

> Should this contain the vertices in the wall face

Yes, the wall vertices should be included.  In the figure I posted, you can see that some wall vertices are not in the list of non-aligned vertices.

> vertices in the private region

The same rules should apply for vertices in the private region.

**Comment by rhager** [comment]
> `/p/epsi/rhager/d3d_132007-01298_v3_20210609.tar`

This is on portal.pppl.gov.
